// This file contains two deliveryTimeCollection objects for testing
module.exports = {
    oberhausenDeliveryTimeCollection: [{
        id: 70,
        dayOfWeek: 0,
        startMinutes: 720,
        endMinutes: 1439
    }, {
        id: 72,
        dayOfWeek: 1,
        startMinutes: 660,
        endMinutes: 1439
    }, {
        id: 74,
        dayOfWeek: 2,
        startMinutes: 660,
        endMinutes: 1439
    }, {
        id: 76,
        dayOfWeek: 3,
        startMinutes: 660,
        endMinutes: 1439
    }, {
        id: 78,
        dayOfWeek: 4,
        startMinutes: 660,
        endMinutes: 1439
    }, {
        id: 80,
        dayOfWeek: 5,
        startMinutes: 660,
        endMinutes: 1439
    }, {
        id: 82,
        dayOfWeek: 6,
        startMinutes: 0,
        endMinutes: 1439
    }, {
        id: 206,
        dayOfWeek: 6,
        startMinutes: 0,
        endMinutes: 45
    }, {
        id: 209,
        dayOfWeek: 5,
        startMinutes: 0,
        endMinutes: 60
    }],

    memmingenDeliveryTimeCollection: [{
        id: 2,
        dayOfWeek: 0,
        startMinutes: 1020,
        endMinutes: 1310
    }, {
        id: 5,
        dayOfWeek: 2,
        startMinutes: 690,
        endMinutes: 830
    }, {
        id: 7,
        dayOfWeek: 3,
        startMinutes: 690,
        endMinutes: 830
    }, {
        id: 142,
        dayOfWeek: 2,
        startMinutes: 1050,
        endMinutes: 1310
    }, {
        id: 143,
        dayOfWeek: 3,
        startMinutes: 1050,
        endMinutes: 1310
    }, {
        id: 182,
        dayOfWeek: 5,
        startMinutes: 690,
        endMinutes: 830
    }, {
        id: 183,
        dayOfWeek: 1,
        startMinutes: 690,
        endMinutes: 830
    }, {
        id: 190,
        dayOfWeek: 6,
        startMinutes: 690,
        endMinutes: 830
    }, {
        id: 192,
        dayOfWeek: 4,
        startMinutes: 690,
        endMinutes: 830
    }, {
        id: 194,
        dayOfWeek: 1,
        startMinutes: 1050,
        endMinutes: 1310
    }, {
        id: 196,
        dayOfWeek: 4,
        startMinutes: 1050,
        endMinutes: 1310
    }, {
        id: 211,
        dayOfWeek: 6,
        startMinutes: 1020,
        endMinutes: 1310
    }, {
        id: 212,
        dayOfWeek: 5,
        startMinutes: 1020,
        endMinutes: 1310
    }]
};
